services:
  telegram-bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    container_name: jira-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./scratch:/usr/src/app/scratch
    environment:
      - TZ=Asia/Ho_Chi_Minh

